/* The example output shown on each workflow card.

   These ship with FlixML and are the same on every install: a card shows what the
   workflow does, not what this particular box has made with it. A fresh install and
   a year-old one look alike, and nothing a user generated is ever the face of a card.

   Every file is generic by rule — landscapes, objects, lettering. No people, no
   faces, no characters. Each was generated by the workflow it illustrates, so the
   picture is an honest sample of that workflow's output rather than stock art. The
   assets live in public/workflow-examples/ and are the same files flixml.com serves
   on its workflow catalog.

   A workflow with no entry here shows what it takes instead of a picture. */

export type WorkflowExample = {
  type: "image" | "video";
  src: string;
  /** Poster for a video. */
  poster?: string;
  alt: string;
};

export const workflowExamples: Record<string, WorkflowExample> = {
  flux2_klein: {
    type: "image",
    src: "/workflow-examples/flux2_klein.webp",
    alt: "A lighthouse on a rocky sea cliff at sunset, waves breaking below.",
  },
  sdxl_base: {
    type: "image",
    src: "/workflow-examples/sdxl_base.webp",
    alt: "A glazed ceramic teapot on a wooden table beside a window in morning light.",
  },
  sdxl_img2img: {
    type: "image",
    src: "/workflow-examples/sdxl_img2img.webp",
    alt: "A blue and white porcelain teapot on the same table and in the same light as the brown one it was generated from.",
  },
  qwen_multiangle: {
    type: "image",
    src: "/workflow-examples/qwen_multiangle.webp",
    alt: "The blue and white porcelain teapot seen from a front-right quarter angle, spout left and handle right.",
  },
  text_logo: {
    type: "image",
    src: "/workflow-examples/text_logo.webp",
    alt: "The word FlixML typeset in green on black.",
  },
  wan22_i2v: {
    type: "video",
    src: "/workflow-examples/wan22_i2v.mp4",
    poster: "/workflow-examples/wan22_i2v.webp",
    alt: "Waves surging over rocks below a lighthouse at sunset, three seconds of motion.",
  },
};
